name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - master # Or your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.4 # Use the latest version
        with:
          github_repo_id: SathvikDixit/Segmentation-of-Teeth-in-Panoramic-X-ray-Image-Using-U-Net
          huggingface_repo_id: DemonsSlayer/DentalSegmentation # Or model/dataset name
          repo_type: space # Or 'model', 'dataset'
          space_sdk: gradio # Or 'streamlit', 'docker', etc. if using Spaces
          hf_token: ${{ secrets.HF_TOKEN }} 
